volumes:
  db_pi:

networks:
  backend_network:
    driver: bridge  

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: pi_fisio
    ports:
      - "3307:3306"  
    networks:
      - backend_network
    volumes:
      - db_pi:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mysql -u${DATABASE_USER} -p${DATABASE_PASSWORD} -e 'SELECT 1;'"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
      
  back_end:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      mysql_db:
        condition: service_healthy 
    container_name: pi_backend
    ports:
      - "8090:8090"  
    environment:
      - MYSQL_URL=mysql_db
      - GOOGLE_SECRET_ID=${GOOGLE_SECRET_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
      - JWT_TOKEN_EXPIRATION=${JWT_TOKEN_EXPIRATION}
    networks:
      - backend_network
    restart: on-failure
